sudo: required
services:
  - docker

before_install:
  - docker build -t modugulakrishna99/docker-react -f Dockerfile.dev .

script:
  - docker run  modugulakrishna99/docker-react npm run test -- --coverage
